### ISSUE TITLE
Plaid Integration

### ISSUE THREAD

**Issue by jhechtf** [sungmanito/mono#28]
## Description

Little exploration has been done on this, but the overall goal is to make is so that someone who is using Sungmanito can link their payment accounts with Plaid, and then map any outgoing transactions to payments for bills. This way we could auto mark bills as paid, updating any household members when the notice is received

## Concerns

While we want the user who has hooked up the account to have management over that account, we also do not want anyone who does not need transaction access to said account to see it.

### Stage 1

- [ ] POC for Plaid integration + transaction mapping
- [ ] POC for account permissions to households

## Stage 2
- [ ] Closed testing for Plaid features

## Stage 3
Assuming everything goes well
- [ ] Open Beta

**Comment by jhechtf** [comment]
It has occurred to me that I'm going to have look into what exactly SOC2 compliance is because I'm not going to want to deal with that bag of shenanigans should this somehow get hacked in a production environment.
